### ISSUE TITLE
Leo Dictionary Helper stopped working with Leo 

### ISSUE THREAD

**Issue by franc3sc0** [psistorm/alfredapp#20]
Dict.leo.org slightly revamped their website on Jan. 5, 2017. Since then, the Leo Dictionary Helper stopped working: no results are returned, no matter what query is entered.

**Comment by woodyc79** [comment]
Same here - would be great if someone fixes this!

**Comment by Akku** [comment]
Got the same problem and am completely lost without this workflow. Sadly, I didn't find what was changed in the APIs or how the new API looks like, it might be pretty easy to fix if you know what changed.

**Comment by PhilippMeyer** [comment]
Wasn't working for me neither but I just re-downloaded it and now it works like a charm.

**Comment by Akku** [comment]
Oh, that's it! Just redownload and you're ready to go!

**Comment by psistorm** [comment]
No more further development will be done because I had to take the workflow down. (See Readme.md in repository for more information)
