### ISSUE TITLE
Provide some kind of donation button

### ISSUE THREAD

**Issue by Xiphe** [psistorm/alfredapp#21]
This is one of the most often used alfred tools I use.

I'd love to buy you a beer or coffee if you provide me some way to do it 😄

**Comment by PhilippMeyer** [comment]
Me too!

**Comment by psistorm** [comment]
No more further development will be done because I had to take the workflow down. (See Readme.md in repository for more information)

**Comment by Xiphe** [comment]
@psistorm that's really sad :(

I'll drop them an email, asking for a donation button and an upgrade to their terms of service :)
